---
title: "Untitled"
author: "Tanner Ball"
date: "12/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
# Multinomial Logistic Regression

# we will try to use multinomial logistic regression to predict how far a team will go in the ncaa tournament.
# we will use the stats in data4, which we've previously determined to all be significant (with the exception of Games Played (G)), as well as some variables that will serve as context later, but not be part of the model.

data <- read.csv("cbb.csv") # data originally acquired from https://www.kaggle.com/andrewsundberg/college-basketball-dataset
ncaa_data <- data[c(1, 3:13, 15, 20:22, 24)]

# we're also going to only look at teams that made the tournament, because the sheer number of non-tournament teams could throw things off.

ncaa_data <- ncaa_data %>% drop_na(POSTSEASON) 

# also, we are going to convert any teams that were R68 but not R64 to be considered the same, because for all intents and purposes, they are. R68 is simply the play-in round to R64, and it is a relatively new development and there are so few teams in that category that I really don't see the point in considering them differently.

ncaa_data$POSTSEASON[ncaa_data$POSTSEASON == "R68"] <- "R64/68"
ncaa_data$POSTSEASON[ncaa_data$POSTSEASON == "R64"] <- "R64/68"

dt <- sort(sample(nrow(ncaa_data), nrow(ncaa_data)*.7))
ncaa_train <- ncaa_data[dt,]
ncaa_test <- ncaa_data[-dt,]

library(nnet)
ncaa_multi <- multinom(POSTSEASON ~ W + ADJOE + ADJDE + EFG_O + EFG_D + TOR + 
                         TORD + ORB + DRB + FTRD + ADJ_T + WAB - 1, data = ncaa_train)
summary(ncaa_multi)

## extracting coefficients from the model and exponentiate
exp(coef(ncaa_multi))

head(probability.table <- fitted(ncaa_multi))

# Predicting the values for train dataset
ncaa_train$predicted <- predict(ncaa_multi, newdata = ncaa_train, "class")

# accuracy of train predictions:
ncaa_train <- ncaa_train %>% mutate(accurate = 1*(POSTSEASON == predicted))
sum(ncaa_train$accurate)/nrow(ncaa_train)

# Predicting the values for test dataset
ncaa_test$predicted <- predict(ncaa_multi, newdata = ncaa_test, "class")

# accuracy of test predictions:
ncaa_test <- ncaa_test %>% mutate(accurate = 1*(POSTSEASON == predicted))
sum(ncaa_test$accurate)/nrow(ncaa_test)

# create dataframe with results - number of teams that actually finished in each way, and the number of teams we correctly predicted to finish in that way
model_results <- setNames(data.frame(matrix(ncol = 3, nrow = 7)), c("Postseason Result", "Number of Teams", "Accurate"))
model_results["Postseason Result"] <- c("Champions", "2nd", "F4", "E8", "S16", "R32", "R64/68")
model_results["Number of Teams"] <- c(nrow(subset(ncaa_test, POSTSEASON == "Champions")), nrow(subset(ncaa_test, POSTSEASON == "2ND")), nrow(subset(ncaa_test, POSTSEASON == "F4")), nrow(subset(ncaa_test, POSTSEASON == "E8")),   nrow(subset(ncaa_test, POSTSEASON == "S16")), nrow(subset(ncaa_test, POSTSEASON == "R32")), nrow(subset(ncaa_test, POSTSEASON == "R64/68")))
model_results["Accurate"] <- c(nrow(subset(ncaa_test, POSTSEASON == "Champions" & accurate == 1)), nrow(subset(ncaa_test, POSTSEASON == "2ND" & accurate == 1)), nrow(subset(ncaa_test, POSTSEASON == "F4" & accurate == 1)), nrow(subset(ncaa_test, POSTSEASON == "E8" & accurate == 1)), nrow(subset(ncaa_test, POSTSEASON == "S16" & accurate == 1)), nrow(subset(ncaa_test, POSTSEASON == "R32" & accurate == 1)), nrow(subset(ncaa_test, POSTSEASON == "R64/68" & accurate == 1)))
model_results <- model_results %>% mutate(Accuracy = Accurate/`Number of Teams`)

model_results$`Postseason Result` <- factor(model_results$`Postseason Result`,levels = c("Champions", "2nd", "F4", "E8", "S16", "R32", "R64/68"))
ggplot(data=model_results, aes(x=`Postseason Result`)) + geom_bar(aes(y=`Number of Teams`), stat="identity", position="identity", alpha=.3, fill='lightblue', color='lightblue4') + geom_text(aes(y = `Number of Teams`, label = `Number of Teams`), vjust = -0.5) + geom_bar(aes(y=Accurate), stat="identity", position="identity", alpha=.8, fill='pink', color='red') + geom_text(aes(y = Accurate, label = round(Accuracy, 2)), vjust = 1.25) + ggtitle("Model Results on Test Data - Number of Teams and Percentage Correctly\nPredicted for each possible NCAA Tournament Finish")
```

```{r}
# Testing the Model on a Specific Tournament, rather than a random assortment of Tournament Teams
ncaa_2019 <- ncaa_data[ncaa_data$YEAR == 2019,]

# Predicting the values for test dataset
ncaa_2019$predicted <- predict(ncaa_multi, newdata = ncaa_2019, "class")

# accuracy of test predictions:
ncaa_2019 <- ncaa_2019 %>% mutate(accurate = 1*(POSTSEASON == predicted))
sum(ncaa_2019$accurate)/nrow(ncaa_2019)

# create dataframe with results - number of teams that actually finished in each way, and the number of teams we correctly predicted to finish in that way
model_results19 <- setNames(data.frame(matrix(ncol = 3, nrow = 7)), c("Postseason Result", "Number of Teams", "Accurate"))
model_results19["Postseason Result"] <- c("Champions", "2nd", "F4", "E8", "S16", "R32", "R64/68")
model_results19["Number of Teams"] <- c(nrow(subset(ncaa_2019, POSTSEASON == "Champions")), nrow(subset(ncaa_2019, POSTSEASON == "2ND")), nrow(subset(ncaa_2019, POSTSEASON == "F4")), nrow(subset(ncaa_2019, POSTSEASON == "E8")),   nrow(subset(ncaa_2019, POSTSEASON == "S16")), nrow(subset(ncaa_2019, POSTSEASON == "R32")), nrow(subset(ncaa_2019, POSTSEASON == "R64/68")))
model_results19["Accurate"] <- c(nrow(subset(ncaa_2019, POSTSEASON == "Champions" & accurate == 1)), nrow(subset(ncaa_2019, POSTSEASON == "2ND" & accurate == 1)), nrow(subset(ncaa_2019, POSTSEASON == "F4" & accurate == 1)), nrow(subset(ncaa_2019, POSTSEASON == "E8" & accurate == 1)), nrow(subset(ncaa_2019, POSTSEASON == "S16" & accurate == 1)), nrow(subset(ncaa_2019, POSTSEASON == "R32" & accurate == 1)), nrow(subset(ncaa_2019, POSTSEASON == "R64/68" & accurate == 1)))
model_results19 <- model_results19 %>% mutate(Accuracy = Accurate/`Number of Teams`)

model_results19$`Postseason Result` <- factor(model_results19$`Postseason Result`,levels = c("Champions", "2nd", "F4", "E8", "S16", "R32", "R64/68"))
ggplot(data=model_results19, aes(x=`Postseason Result`)) + geom_bar(aes(y=`Number of Teams`), stat="identity", position="identity", alpha=.3, fill='lightblue', color='lightblue4') + geom_text(aes(y = `Number of Teams`, label = `Number of Teams`), vjust = -0.5) + geom_bar(aes(y=Accurate), stat="identity", position="identity", alpha=.8, fill='pink', color='red') + geom_text(aes(y = Accurate, label = round(Accuracy, 2)), vjust = 1.25) + ggtitle("Model Results on 2019 NCAA Tournament")
```
